---
title: "02_d4_d9_analysis"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pheatmap)
library(tidyverse)
library(ggplot2)
library(DESeq2)
library(dplyr)
```

D4 vs D9 dataset - new nextflow run with updated annotation (2022)
RNA-seq data from Pereira et al., 2018

Let's run deseq in this comparison
```{r - prep}
#read in counts
counts_d4_d9 <- read.table("/scratch/Shares/rinn/isabela/CARDEL/d4_d9/results/star_salmon/salmon.merged.gene_counts.tsv", header = T)

counts_d4_d9 <- counts_d4_d9 %>%
  column_to_rownames(var = "gene_id") %>%
  select(-gene_name)

#clean those with all 0 counts
counts_d4_d9 <- counts_d4_d9[rowSums(counts_d4_d9) > 0,]

#samples
sample <- c("D4_R1", "D4_R2", "D4_R3", "D9_R1", "D9_R2", "D9_R3")
day <- c("D4","D4", "D4", "D9", "D9", "D9")
replicate <- c("R1", "R2", "R3", "R1", "R2", "R3")

sample <- data.frame(sample, day, replicate)

#transform comparisons in factor for deseq
factor_1 <- c("D4", "D9")
sample$day <- factor(sample$day, levels = factor_1 )

```

```{r - deseq}
#reordering and checking sample_id (it MUST be the same order in both)
sample$sample <- as.character(sample$sample)

all(colnames(counts_d4_d9) == sample$sample)

#change to matrix
counts_d4_d9 <- as.matrix(counts_d4_d9)

# Now we need to round the values and change to integer from numeric.
counts_d4_d9 <- round(counts_d4_d9)

# change counts to integer (this is required by DESeq)
mode(counts_d4_d9) <- "integer"


# Run DESEq

dds <- DESeqDataSetFromMatrix(counts_d4_d9, sample,
                              design = ~ day)
dds_run <- DESeq(dds)
resultsNames(dds_run)

#save analysis
write_rds(dds_run, "/scratch/Shares/rinn/isabela/CARDEL/d4_d9/deseq_d4_d9.rds")

d4_d9_deseq <- as.data.frame(results(dds_run, name = "day_D9_vs_D4")) %>%
  rownames_to_column(var = "gene_id") %>%
  left_join(gene_name)

#save table
write.csv(d4_d9_deseq, "/scratch/Shares/rinn/isabela/CARDEL/d4_d9/d4_d9_deseq_results.csv")

# extract rlog_counts if want to plot heatmaps
rlog_counts <- dds %>%
  rlog() %>%
  assay() %>%
  as.data.frame() 

#save rlog_counts
write_rds(rlog_counts,"/scratch/Shares/rinn/isabela/CARDEL/d4_d9/d4_d9_rlog_counts.csv" )


```

```{r}
#tpm
tpmD4_D9 <- read.table("/scratch/Shares/rinn/isabela/CARDEL/d4_d9/results/star_salmon/salmon.merged.gene_tpm.tsv", header = T)

tpm_diff <- tpmD4_D9 %>%
  pivot_longer(cols = D4_R1:D9_R3, names_to = "sample", values_to = "tpm") %>%
  left_join(sample) %>%
  group_by(gene_id, day) %>% ####mean by tissue
  mutate(mean_tpm_diff = mean(tpm)) %>%
  mutate(sd_diff = sd(tpm, na.rm=TRUE))

write_csv(tpm_diff, "/scratch/Shares/rinn/isabela/CARDEL/fetal_adult/analysis/tpm_mean_diff.csv")
```
